### ISSUE TITLE
latest v2 version or BS explanation

### ISSUE THREAD

**Issue by woulf** [sowbug/archer-c9-back-to-stock#5]
Hello,
i'm trying to have a revert to stock version for the v2 but for the latest version (2017-05-11)
i don't get how you calculate the BS in the DD command, could you explain it?
If not could you generate a new webflash using the last tp-link firmware?
thanks

**Comment by sowbug** [comment]
Please look at the v3 instructions, which explain in detail (example: `The 1916901 figure is 2158029 - 241128`). I did v3 first because that's my own router, and then I repeated but without the explanations for the other versions.

**Comment by sowbug** [comment]
Turned out to be easy enough to generate the 170511 version. As with most of these images, I haven't tested it because I don't own that version of the router.
